# SPDX-License-Identifier: MIT
"""Pure generation function. Stable output, hash-verifiable."""

from __future__ import annotations

import hashlib
from typing import TYPE_CHECKING

from .errors import TemplateNotFoundError
from .schema import (
    FingerprintResult,
    GenerateOptions,
    GitignoreOutput,
    Rule,
    RuleSource,
)
from .version import CORE_VERSION

if TYPE_CHECKING:
    from collections.abc import Iterable

    from .ports import RulesTable, TemplateRepository

__all__ = ["generate"]


def generate(
    fingerprint: FingerprintResult,
    options: GenerateOptions,
    *,
    templates: TemplateRepository,
    rules_table: RulesTable,
) -> GitignoreOutput:
    """Generate a `.gitignore`. Pure: same inputs -> byte-identical output.

    Determinism contract
    --------------------
    For fixed ``(fingerprint, options, templates_version, rules_table_version)``
    this function is a pure function of its arguments: no I/O, no clock,
    no env vars, no random. The implementation explicitly sorts before
    every iteration that contributes to the output.
    """
    feature_set = frozenset(fingerprint.features)
    collected: list[Rule] = []

    for feature in sorted(feature_set):
        try:
            collected.extend(templates.get(feature))
        except TemplateNotFoundError:
            # A fingerprint may declare features for which the repository
            # has no template (e.g. user-supplied detectors). Skip silently
            # — the rules table can still contribute patterns for them.
            continue

    collected.extend(rules_table.extras_for(feature_set))

    collected.extend(
        Rule(pattern=extra, source=RuleSource.USER_EXTRA) for extra in options.extras
    )

    ordered = _stable_dedup(collected)
    content = _render(
        ordered,
        options,
        core_version=CORE_VERSION,
        templates_version=templates.version(),
        rules_table_version=rules_table.version(),
    )
    content_hash = f"sha256:{hashlib.sha256(content.encode('utf-8')).hexdigest()}"
    provenance_hash = _provenance_hash(
        core_version=CORE_VERSION,
        templates_version=templates.version(),
        rules_table_version=rules_table.version(),
        content_hash=content_hash,
    )
    return GitignoreOutput(
        content=content,
        rules=ordered,
        content_hash=content_hash,
        provenance_hash=provenance_hash,
        rules_table_version=rules_table.version(),
        templates_version=templates.version(),
        core_version=CORE_VERSION,
    )


def _provenance_hash(
    *,
    core_version: str,
    templates_version: str,
    rules_table_version: str,
    content_hash: str,
) -> str:
    """Merkle-style commitment over the full provenance chain."""
    digest = hashlib.sha256()
    for part in (core_version, templates_version, rules_table_version, content_hash):
        digest.update(part.encode("utf-8"))
        digest.update(b"\x00")
    return f"sha256:{digest.hexdigest()}"


_SOURCE_ORDER: dict[RuleSource, int] = {
    RuleSource.TEMPLATE: 0,
    RuleSource.MINED: 1,
    RuleSource.USER_EXTRA: 2,
}


def _stable_dedup(rules: Iterable[Rule]) -> tuple[Rule, ...]:
    by_pattern: dict[str, Rule] = {}
    for rule in rules:
        # First occurrence wins (preserves provenance from the highest-priority source).
        by_pattern.setdefault(rule.pattern, rule)
    return tuple(
        sorted(by_pattern.values(), key=_sort_key),
    )


def _sort_key(rule: Rule) -> tuple[int, bool, str]:
    """Total, deterministic order for a rule.

    Within a source section, negation patterns (``!foo``) are emitted *after*
    the positive patterns. git resolves ignore status by "last matching pattern
    wins", so a re-include like ``!.env.example`` only takes effect if it follows
    the ``.env.*`` that excluded it. Sorting purely alphabetically would place
    ``!`` (0x21) before ``.`` / ``*`` and silently neuter every negation. This
    keeps the output deterministic while making negations semantically correct.
    """
    return (_SOURCE_ORDER[rule.source], rule.pattern.startswith("!"), rule.pattern)


_HEADER = "# Generated by occam-gitignore. Deterministic. Do not edit by hand."


def _render(
    rules: tuple[Rule, ...],
    options: GenerateOptions,
    *,
    core_version: str,
    templates_version: str,
    rules_table_version: str,
) -> str:
    lines: list[str] = []
    if options.include_comments:
        lines.append(_HEADER)
        # Provenance line: lets a reader/audit verify reproducibility by
        # re-running with the same versions. Always present whenever
        # comments are enabled.
        lines.append(
            f"# core={core_version} templates={templates_version} "
            f"rules_table={rules_table_version}",
        )
    current_section: RuleSource | None = None
    for rule in rules:
        if options.include_comments and rule.source is not current_section:
            lines.append("")
            lines.append(f"# --- {rule.source.value} ---")
            current_section = rule.source
        suffix = ""
        if options.include_provenance and rule.feature is not None:
            suffix = f"  # {rule.feature}"
        lines.append(f"{rule.pattern}{suffix}")
    lines.append("")
    return "\n".join(lines)
